using Astrolabe.Domain.Abstractions;

namespace Astrolabe.Domain.Features.Recommendations.Events;

/// <summary>
/// A library stopped offering model-generated recommendations. BR-REC-012.
///
/// Exists so "immediate" is enforced in one place: a handler evicts the cached sets that were
/// generated by this library, and no caller has to remember that switching off is not enough on its
/// own. Carries an identifier only, never an entity.
/// </summary>
public sealed record LibraryAiDisabled(
    Guid EventId,
    DateTimeOffset OccurredAt,
    Guid LibraryId) : IDomainEvent;
