// <auto-generated />
using System;
using Astrolabe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Astrolabe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AstrolabeDbContext))]
    [Migration("20260816021829_AddNetworkDomain")]
    partial class AddNetworkDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("astrolabe")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.AdminInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.PrimitiveCollection<Guid[]>("LibraryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("library_ids");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_invitations");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_admin_invitations_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_admin_invitations_user_id");

                    b.ToTable("admin_invitations", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<Guid?>("HomeLibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_library_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_country_id_name");

                    b.ToTable("cities", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsHiddenFromRegistration")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden_from_registration");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_iso_code");

                    b.ToTable("countries", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_libraries_is_active");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_libraries_city_id_name");

                    b.ToTable("libraries", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.LibraryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_library_assignments");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_library_assignments_library_id");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique()
                        .HasDatabaseName("ix_library_assignments_user_id_library_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_library_assignments_user_id_revoked_at");

                    b.ToTable("library_assignments", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.City", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Network.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cities_countries_country_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Library", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Network.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_cities_city_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.LibraryAssignment", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Network.Library", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_library_assignments_libraries_library_id");
                });
#pragma warning restore 612, 618
        }
    }
}
