// <auto-generated />
using System;
using System.Collections.Generic;
using Astrolabe.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Astrolabe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AstrolabeDbContext))]
    [Migration("20260816060612_AddReservationsDomain")]
    partial class AddReservationsDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("astrolabe")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Astrolabe.Domain.Features.Audit.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SubjectUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_user_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_entries");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_entries_action");

                    b.HasIndex("SubjectUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_subject_user_id_occurred_at");

                    b.ToTable("audit_entries", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author");

                    b.Property<decimal?>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("genre");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("tier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RetailPrice", "Astrolabe.Domain.Features.Catalog.Entities.Book.RetailPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Cents")
                                .HasColumnType("bigint")
                                .HasColumnName("retail_price_cents");
                        });

                    b.HasKey("Id")
                        .HasName("pk_books");

                    b.HasIndex("Status", "Genre")
                        .HasDatabaseName("ix_books_status_genre");

                    b.ToTable("books", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.BookCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableCount")
                        .HasColumnType("integer")
                        .HasColumnName("available_count");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_count");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_book_copies");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_book_copies_library_id");

                    b.HasIndex("BookId", "LibraryId")
                        .IsUnique()
                        .HasDatabaseName("ix_book_copies_book_id_library_id");

                    b.ToTable("book_copies", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.HasKey("Id")
                        .HasName("pk_reviews");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_reviews_member_id");

                    b.HasIndex("BookId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviews_book_id_member_id");

                    b.ToTable("reviews", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_refresh_tokens_session_id");

                    b.ToTable("refresh_tokens", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.SingleUseToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_single_use_tokens");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_single_use_tokens_hash");

                    b.HasIndex("UserId", "Purpose", "ConsumedAt", "InvalidatedAt")
                        .HasDatabaseName("ix_single_use_tokens_user_id_purpose_consumed_at_invalidated_at");

                    b.ToTable("single_use_tokens", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<int>("FailedSignInAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_sign_in_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TotpSecret")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("totp_secret");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email")
                        .HasFilter("status <> 3");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApproximateLocation")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("approximate_location");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int?>("RevokedReason")
                        .HasColumnType("integer")
                        .HasColumnName("revoked_reason");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_user_sessions_user_id_revoked_at");

                    b.ToTable("user_sessions", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Membership.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CityChangesThisCycle")
                        .HasColumnType("integer")
                        .HasColumnName("city_changes_this_cycle");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("plan");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_member_id")
                        .HasFilter("ended_at IS NULL");

                    b.ToTable("subscriptions", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.AdminInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by_user_id");

                    b.PrimitiveCollection<Guid[]>("LibraryIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("library_ids");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_invitations");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_admin_invitations_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_admin_invitations_user_id");

                    b.ToTable("admin_invitations", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<Guid?>("HomeLibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_library_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cities");

                    b.HasIndex("CountryId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cities_country_id_name");

                    b.ToTable("cities", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsHiddenFromRegistration")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden_from_registration");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("iso_code")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("IsoCode")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_iso_code");

                    b.ToTable("countries", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_libraries");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_libraries_is_active");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_libraries_city_id_name");

                    b.ToTable("libraries", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.LibraryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_library_assignments");

                    b.HasIndex("LibraryId")
                        .HasDatabaseName("ix_library_assignments_library_id");

                    b.HasIndex("UserId", "LibraryId")
                        .IsUnique()
                        .HasDatabaseName("ix_library_assignments_user_id_library_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_library_assignments_user_id_revoked_at");

                    b.ToTable("library_assignments", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Reservations.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookCopyId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_copy_id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<int>("DaysLateAtCheckIn")
                        .HasColumnType("integer")
                        .HasColumnName("days_late_at_check_in");

                    b.Property<string>("Delivery")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("delivery");

                    b.Property<DateTimeOffset?>("HandedOverAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("handed_over_at");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid")
                        .HasColumnName("library_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("ReturnMethod")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("return_method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DeliveryFee", "Astrolabe.Domain.Features.Reservations.Entities.Reservation.DeliveryFee#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Cents")
                                .HasColumnType("bigint")
                                .HasColumnName("delivery_fee_cents");
                        });

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("BookCopyId")
                        .HasDatabaseName("ix_reservations_book_copy_id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_reservations_book_id");

                    b.HasIndex("LibraryId", "Status")
                        .HasDatabaseName("ix_reservations_library_id_status");

                    b.HasIndex("MemberId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_reservations_member_id_idempotency_key")
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("MemberId", "Status")
                        .HasDatabaseName("ix_reservations_member_id_status");

                    b.ToTable("reservations", "astrolabe");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.Book", b =>
                {
                    b.OwnsOne("Astrolabe.Domain.Features.Catalog.ValueObjects.Isbn", "Isbn", b1 =>
                        {
                            b1.Property<Guid>("BookId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(13)
                                .HasColumnType("character varying(13)")
                                .HasColumnName("isbn");

                            b1.HasKey("BookId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_books_isbn");

                            b1.ToTable("books", "astrolabe");

                            b1.WithOwner()
                                .HasForeignKey("BookId")
                                .HasConstraintName("fk_books_books_id");
                        });

                    b.Navigation("Isbn")
                        .IsRequired();
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.BookCopy", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Catalog.Entities.Book", null)
                        .WithMany("Copies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_copies_books_book_id");

                    b.HasOne("Astrolabe.Domain.Features.Network.Entities.Library", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_book_copies_libraries_library_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.Review", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Catalog.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_books_book_id");

                    b.HasOne("Astrolabe.Domain.Features.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviews_users_member_id");

                    b.OwnsOne("Astrolabe.Domain.Features.Catalog.ValueObjects.StarRating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ReviewId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("Stars")
                                .HasColumnType("integer")
                                .HasColumnName("rating");

                            b1.HasKey("ReviewId");

                            b1.ToTable("reviews", "astrolabe");

                            b1.WithOwner()
                                .HasForeignKey("ReviewId")
                                .HasConstraintName("fk_reviews_reviews_id");
                        });

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.RefreshToken", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Identity.Entities.UserSession", null)
                        .WithMany("Tokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_user_sessions_session_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.SingleUseToken", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_single_use_tokens_users_user_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.UserSession", b =>
                {
                    b.OwnsOne("Astrolabe.Domain.Features.Identity.ValueObjects.DeviceDescriptor", "Device", b1 =>
                        {
                            b1.Property<Guid>("UserSessionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ClientDeviceId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("client_device_id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("device_name");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("device_type");

                            b1.HasKey("UserSessionId");

                            b1.ToTable("user_sessions", "astrolabe");

                            b1.WithOwner()
                                .HasForeignKey("UserSessionId")
                                .HasConstraintName("fk_user_sessions_user_sessions_id");
                        });

                    b.Navigation("Device")
                        .IsRequired();
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Membership.Entities.Subscription", b =>
                {
                    b.OwnsOne("Astrolabe.Domain.Features.Membership.ValueObjects.BillingCycle", "Cycle", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("AnchorDay")
                                .HasColumnType("integer")
                                .HasColumnName("cycle_anchor_day");

                            b1.Property<DateTimeOffset>("RenewsOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("cycle_renews_on");

                            b1.Property<DateTimeOffset>("StartedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("cycle_started_on");

                            b1.HasKey("SubscriptionId");

                            b1.HasIndex("RenewsOn")
                                .HasDatabaseName("ix_subscriptions_cycle_renews_on")
                                .HasFilter("ended_at IS NULL");

                            b1.ToTable("subscriptions", "astrolabe");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId")
                                .HasConstraintName("fk_subscriptions_subscriptions_id");
                        });

                    b.OwnsOne("Astrolabe.Domain.Features.Membership.ValueObjects.ScheduledPlanChange", "ScheduledChange", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("EffectiveOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("scheduled_change_effective_on");

                            b1.Property<DateTimeOffset>("RequestedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("scheduled_change_requested_at");

                            b1.Property<string>("Target")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("scheduled_change_target");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("subscriptions", "astrolabe");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId")
                                .HasConstraintName("fk_subscriptions_subscriptions_id");
                        });

                    b.Navigation("Cycle")
                        .IsRequired();

                    b.Navigation("ScheduledChange");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.City", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Network.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cities_countries_country_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.Library", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Network.Entities.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_libraries_cities_city_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Network.Entities.LibraryAssignment", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Network.Entities.Library", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_library_assignments_libraries_library_id");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Reservations.Entities.Reservation", b =>
                {
                    b.HasOne("Astrolabe.Domain.Features.Catalog.Entities.BookCopy", null)
                        .WithMany()
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_book_copies_book_copy_id");

                    b.HasOne("Astrolabe.Domain.Features.Catalog.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_books_book_id");

                    b.HasOne("Astrolabe.Domain.Features.Network.Entities.Library", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_libraries_library_id");

                    b.HasOne("Astrolabe.Domain.Features.Identity.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_users_member_id");

                    b.OwnsOne("Astrolabe.Domain.Features.Reservations.ValueObjects.LoanPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("DueOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("due_on");

                            b1.Property<DateTimeOffset>("StartedOn")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("borrowed_on");

                            b1.HasKey("ReservationId");

                            b1.HasIndex("DueOn")
                                .HasDatabaseName("ix_reservations_due_on");

                            b1.ToTable("reservations", "astrolabe");

                            b1.WithOwner()
                                .HasForeignKey("ReservationId")
                                .HasConstraintName("fk_reservations_reservations_id");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Catalog.Entities.Book", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Astrolabe.Domain.Features.Identity.Entities.UserSession", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
